# This module was generated by 'terragrunt scaffold'
# TODO: Regeneration instructions
{{- $IgnoreMap := dict "" false }}
{{- $AlreadyProcessedNames := dict "" false }}
{{- range .IgnoredVariables }}
  {{- $IgnoreMap = merge $IgnoreMap (dict . true) }}
{{- end }}
module "{{ .ModuleInvocationName }}" {
  source  = "{{ .sourceUrl }}"

  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
  {{ range .requiredVariables }}
  {{- if and (not (index $IgnoreMap .Name)) (not (index $AlreadyProcessedNames .Name)) }}
  {{- $AlreadyProcessedNames = merge $IgnoreMap (dict .Name true) }}
  {{- if eq 1 (regexSplit "\n" .Description -1 | len ) }}
  # Description: {{ .Description }}
  {{- else }}
  # Description:
    {{- range $line := regexSplit "\n" .Description -1 }}
    # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
  # Type: {{ .Type }}
  {{- if index $Defaults .Name }}
    {{ .Name }} = try(var.{{ $.ModuleInputVar }}.{{ .Name }}, {{ index $Defaults .Name }})
  {{- else}}
    {{ .Name }} = var.{{ $.ModuleInputVar }}.{{ .Name }}
  {{-end}}
  {{ .Name }} = var.{{ $.ModuleInputVar }}.{{ .Name }}
  {{- end }}
  {{ end }}

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------
  {{ range $v := .optionalVariables }}
  {{- if and (not (index $IgnoreMap .Name)) (not (index $AlreadyProcessedNames .Name)) }}
  {{- $AlreadyProcessedNames = merge $IgnoreMap (dict .Name true) }}
  {{- if eq 1 (regexSplit "\n" .Description -1 | len ) }}
  # Description: {{ .Description }}
  {{- else }}
  # Description:
    {{- range $line := regexSplit "\n" .Description -1 }}
    # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
  # Type: {{ .Type }}
  {{- if index $Defaults .Name }}
    {{ .Name }} = lookup(var.{{ $.ModuleInputVar }}, "{{ .Name }}", {{ index $Defaults .Name }})
  {{- else}}
    {{ .Name }} = lookup(var.{{ $.ModuleInputVar }}, "{{ .Name }}", {{ .DefaultValue }})
  {{-end}}
  {{- end }}
  {{ end }}
}
{{- if .OutputName}}

output "{{ .OutputName }}" {
  description = "Outputs of from the {{ .ModuleInvocationName }} module"
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if not contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}

{{- if .SensitiveOutputs }}

output "{{ .OutputName }}_sensitive" {
  description = "Outputs of from the {{ .ModuleInvocationName }} module"
  sensitive   = true
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}
{{ end }}
{{ end }}
