# This module was generated by 'terragrunt scaffold'
# TODO: Regeneration instructions

{{ $IgnoreMap := make(map[string]string) }}
{{ range . := .IgnoredVariables }}
  {{ $IgnoreMap = merge $IgnoreMap (dict (printf "item_%s" .) true) }}
{{ end }}
# IgnoreMap {{ $IgnoreMap }}
module "{{ .ModuleInvocationName }}" {
  source  = "{{ .sourceUrl }}"

  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
  {{ range .requiredVariables }}
  {{- if not $IgnoreMap. }}
  # {{printf "var %#v" .}}
  {{- if eq 1 (regexSplit "\n" .Description -1 | len ) }}
  # Description: {{ .Description }}
  {{- else }}
  # Description:
    {{- range $line := regexSplit "\n" .Description -1 }}
    # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
  # Type: {{ .Type }}
  {{ .Name }} = var.{{ $.ModuleInputVar }}.{{ .Name }}
  {{- end }}
  {{ end }}

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------
  {{ range .optionalVariables }}
  {{- if not $IgnoreMap. }}
  {{- if eq 1 (regexSplit "\n" .Description -1 | len ) }}
  # Description: {{ .Description }}
  {{- else }}
  # Description:
    {{- range $line := regexSplit "\n" .Description -1 }}
    # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
  # Type: {{ .Type }}
  {{ .Name }} = try(var.{{ $.ModuleInputVar }}.{{ .Name }}, {{ .DefaultValue }})
  {{- end }}
  {{ end }}
}

{{- if not .OutputName}}
output "{{ .OutputName }}" {
  description = "Outputs of from the {{ . ModuleInvocationName }} module"
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if not contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}

{{- if .SensitiveOutputs }}
output "{{ .OutputName }}_sensitive" {
  description = "Outputs of from the {{ . ModuleInvocationName }} module"
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}

{{ end }}