# This module was generated by 'terragrunt scaffold'
# TODO: Regeneration instructions

{{ $IgnoreMap := dict "" false }}
{{ range .IgnoredVariables }}
  {{ $IgnoreMap = merge $IgnoreMap (dict . true) }}
{{ end }}
# IgnoreMap {{ $IgnoreMap }}
module "{{ .ModuleInvocationName }}" {
  source  = "{{ .sourceUrl }}"

  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
  {{ range $v := .requiredVariables }}
  {{- if not $IgnoreMap.$v }}
  {{- if eq 1 (regexSplit "\n" $v.Description -1 | len ) }}
  # Description: {{ $v.Description }}
  {{- else }}
  # Description:
    {{- range $line := regexSplit "\n" $v.Description -1 }}
    # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
  # Type: {{ $v.Type }}
  {{ $v.Name }} = var.{{ $.ModuleInputVar }}.{{ $v.Name }}
  {{- end }}
  {{ end }}

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------
  {{ range $v := .optionalVariables }}
  {{- if not $IgnoreMap.$v }}
  {{- if eq 1 (regexSplit "\n" $v.Description -1 | len ) }}
  # Description: {{ .Description }}
  {{- else }}
  # Description:
    {{- range $line := regexSplit "\n" $v.Description -1 }}
    # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
  # Type: {{ $v.Type }}
  {{ $v.Name }} = try(var.{{ $.ModuleInputVar }}.{{ $v.Name }}, {{ $v.DefaultValue }})
  {{- end }}
  {{ end }}
}

{{- if not .OutputName}}
output "{{ .OutputName }}" {
  description = "Outputs of from the {{ . ModuleInvocationName }} module"
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if not contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}

{{- if .SensitiveOutputs }}
output "{{ .OutputName }}_sensitive" {
  description = "Outputs of from the {{ . ModuleInvocationName }} module"
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}

{{ end }}