# This module was generated by 'terragrunt scaffold'. Do not modify directly
{{- if .HowToUpdate }}
  {{- if eq 1 (regexSplit "\n" .HowToUpdate -1 | len ) }}
    # To Update: {{ .HowToUpdate }}
  {{- else }}
    # To Update:
    {{- range $line := regexSplit "\n" .HowToUpdate -1 }}
      # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
{{- end}}
{{- $IgnoreMap := dict "" false }}
{{- $AlreadyProcessedNames := dict "" false }}
{{- range .IgnoredVariables }}
  {{- $IgnoreMap = merge $IgnoreMap (dict . true) }}
{{- end }}
module "{{ .ModuleInvocationName }}" {
  source  = "{{ .sourceUrl }}"

  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
  {{- range .requiredVariables }}
    {{- if and (not (index $IgnoreMap .Name)) (not (index $AlreadyProcessedNames .Name)) }}
      {{- $AlreadyProcessedNames = merge $IgnoreMap (dict .Name true) }}
      {{- if eq 1 (regexSplit "\n" .Description -1 | len ) }}
        # Description: {{ .Description }}
      {{- else }}
        # Description:
        {{- range $line := regexSplit "\n" .Description -1 }}
          # {{ $line | indent 2 }}
        {{- end }}
      {{- end }}
      # Type: {{ .Type }}
      {{- if index $.HardCode .Name }}
        # Overridden value
        {{ .Name }} = {{ index $.HardCode .Name }}
      {{- else if index $.Defaults .Name }}
        # Default value provided for normally required input
        {{ .Name }} = try(var.{{ $.ModuleInputVar }}.{{ .Name }}, {{ index $.Defaults .Name }})
      {{- else}}
        {{ .Name }} = var.{{ $.ModuleInputVar }}.{{ .Name }}
      {{ end}}
    {{- end }}
  {{- end }}

  # --------------------------------------------------------------------------------------------------------------------
  # Optional inputs
  # Accept user from var.{{ $.ModuleInputVar }}, or provide a default
  # Hard coded values are annoted
  # --------------------------------------------------------------------------------------------------------------------
  {{- range $v := .optionalVariables }}
    {{- if and (not (index $IgnoreMap .Name)) (not (index $AlreadyProcessedNames .Name)) }}
      {{- $AlreadyProcessedNames = merge $IgnoreMap (dict .Name true) }}
      {{- if eq 1 (regexSplit "\n" .Description -1 | len ) }}
        # Description: {{ .Description }}
      {{- else }}
        # Description:
        {{- range $line := regexSplit "\n" .Description -1 }}
          # {{ $line | indent 2 }}
        {{- end }}
      {{- end }}
      # Type: {{ .Type }}
      {{- if index $.HardCode .Name }}
        # Hard coded value
        {{ .Name }} = {{ index $.HardCode .Name }}
      {{- else if index $.Defaults .Name }}
        # Non-standard default value
        {{ .Name }} = try(var.{{ $.ModuleInputVar }}.{{ .Name }}, {{ index $.Defaults .Name }})
      {{- else}}
        {{ .Name }} = try(var.{{ $.ModuleInputVar }}.{{ .Name }}, {{ .DefaultValue }})
      {{ end}}
    {{- end }}
  {{- end }}
}
