# This module was generated by 'terragrunt scaffold'. Do not modify directly
{{- if .HowToUpdate }}
  {{- if eq 1 (regexSplit "\n" .HowToUpdate -1 | len ) }}
    # To Update: {{ .HowToUpdate }}
  {{- else }}
    # To Update:
    {{- range $line := regexSplit "\n" .HowToUpdate -1 }}
      # {{ $line | indent 2 }}
    {{- end }}
  {{- end }}
{{- end}}
{{- $IgnoreMap := dict "" false }}
{{- $AlreadyProcessedNames := dict "" false }}
{{- range .IgnoredVariables }}
  {{- $IgnoreMap = merge $IgnoreMap (dict . true) }}
{{- end }}
{{- if .OutputName}}

output "{{ .OutputName }}" {
  description = "Non-senstive outputs from module {{ .ModuleInvocationName }}"
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if !contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}

{{- if .SensitiveOutputs }}

output "{{ .OutputName }}_sensitive" {
  description = "Sensitive outputs from module {{ .ModuleInvocationName }}"
  sensitive   = true
  value       = {
    for k, v in module.{{ .ModuleInvocationName }}:
      k => v
      if contains([{{ range .SensitiveOutputs }} "{{ . }}", {{ end }}], k)
  }
}
{{- end }}
{{- end }}
